title: "VC Firms Database"
description: "A database of venture capital firms"
baseurl: "/vc-firms-database"
url: "https://projectstartups.github.io"
permalink: /:year/:month/:day/:title/

theme: jekyll-theme-minima
